/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingInformation = IDL.Record({ 'text' : IDL.Text });
export const ContactInformation = IDL.Record({
  'mail' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBookingInformation' : IDL.Func([], [BookingInformation], ['query']),
  'getContactInformation' : IDL.Func([], [ContactInformation], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingInformation = IDL.Record({ 'text' : IDL.Text });
  const ContactInformation = IDL.Record({
    'mail' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getBookingInformation' : IDL.Func([], [BookingInformation], ['query']),
    'getContactInformation' : IDL.Func([], [ContactInformation], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };